Disable pro_pick recipe when it is disabled
Forge blows logs with error due to item used in recipe but being not registered when it is disabled in configs:
```
[Server thread/ERROR] [FML]: Parsing error loading recipe geolosys:pro_pick
com.google.gson.JsonSyntaxException: Unknown item 'geolosys:pro_pick'
...
```